FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy the rest of the frontend code
COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]
