FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy the rest of the frontend code
COPY . .

RUN npm run build
RUN npm install -g serve

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
