version: '3.8'

services:
  openmanus-api:
    container_name: openmanus-api
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - manus-network

  openmanus-frontend:
    container_name: openmanus-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      # - VITE_API_BASE_URL=http://192.168.30.52:8000
      - VITE_API_BASE_URL=http://openmanus-api:8000
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    command: ["serve", "-s", "dist", "-l", "3000"]
    networks:
      - manus-network

networks:
  manus-network:
    driver: bridge
